name: Cross OS builder

run-name: Cross build  ${{github.repository}} by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build on ${{matrix.os}}

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.16'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            g++ \
            make \
            pkg-config \
            libgl1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            ocl-icd-opencl-dev \
            opencl-headers

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install opencl-headers ocl-icd

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Setup Visual Studio
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: CMake
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019"

      - name: CMake
        if: runner.os != 'Windows'
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .
